name: Build docker-manager

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read VERSION file
        id: read_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build binaries
        run: bash build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_version.outputs.version }}
          release_name: Release ${{ steps.read_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          for file in build/*; do
            if [ -f "$file" ]; then
              echo "Uploading $file"
                gh release upload ${{ steps.read_version.outputs.version }} "$file" --repo ${{ github.repository }}
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}