name: Build docker-manager

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build binaries
        run: |
          bash build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-manager-binaries
          path: build/